### ISSUE TITLE
CS:GO chat color

### ISSUE THREAD

**Issue by winniethepoohbear** [altexdim/sourcemod-plugin-gungame#1]
After the CS:GO update to 1.30.0.0 setting chat colors with SM can no longer be set with the \x0B character. A space(or any other character) has to be used in front of the color code.

https://forums.alliedmods.net/showpost.php?p=2017281&postcount=17

stock CPrintToChatEx should be updated to reflect this.

**Comment by altexdim** [comment]
Can you please post fixed version of colors.inc?
