### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by kilroy98** [altexdim/sourcemod-plugin-gungame#5]
### 
// gungame/util.sp(1272) : warning 213: tag mismatch
// gungame/util.sp(1386) : warning 234: symbol "GetClientAuthString" is marked a
s deprecated: Use GetClientAuthId
//
// gungame/offset.sp(10) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// gungame/offset.sp(17) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// gungame/offset.sp(24) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// gungame/offset.sp(52) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// gungame/offset.sp(62) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// gungame/offset.sp(70) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// gungame/offset.sp(78) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// gungame/offset.sp(86) : warning 234: symbol "FindSendPropOffs" is marked as d
eprecated: Use FindSendPropInfo instead, or HasEntProp if you just want to check
 for existence.
//
// C:\Users\Admin\Desktop\sourcemod-1.8.0-git5963-linux\addons\sourcemod\scripti
ng\gungame.sp(298) : warning 234: symbol "GetClientAuthString" is marked as depr
ecated: Use GetClientAuthId

SourceMod 1.8.0 | Game: CSSv34

**Comment by altexdim** [comment]
Warnings, not errors.
